name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IO_TOKEN }}
      - name: Docker pull and push
        run: |
          docker pull gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.2.3-rc.1  
          docker tag  gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.2.3-rc.1  ghcr.io/oriapps/cloud-provider-vsphere/csi/release/syncer:v2.2.3-rc.1       
          docker push ghcr.io/oriapps/cloud-provider-vsphere/csi/release/syncer:v2.2.3-rc.1
